---
apiVersion: v1
kind: Secret
metadata:
  name: config-secret
data:
  .dockerconfigjson: >-
   ewoJImF1dGhzIjogewoJCSJnaXRsYWIuZGlnaXRhbC5za2lsbHM6NTA1MCI6IHsKCQkJImF1dGgiOiAiYkdGMmNtOTJMWE56YkRwUVFITnpkekJ5WkRFPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
