version: '3.7'

services:
        nextcloud:
                image: nextcloud
                depends_on:
                        - db
                ports:
                        - 8080:80
                environment:
                        - MYSQL_HOST=db:3306
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_ROOT_PASSWORD=P@ssw0rd
                volumes:
                        - /mnt/nextcloud:/var/www/html:cached
                        - /mnt/nextapps:/var/www/html/custom_apps:cached
                        - /mnt/nextdata:/var/www/html/data:cached
                        - /mnt/nextconfig:/var/www/html/config:cached

        db:
                image: mariadb:10.5
                restart: always
                # command: --transaction-isolation=READ-COMITTED
                # --binlog-format=ROW
                volumes:
                        - /mnt/db:/var/lib/mysql:cached
                environment:
                        - MYSQL_ROOT_PASSWORD=P@ssw0rd
                        - MYSQL_PASSWORD=P@ssw0rd
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
volumes:
        nextcloud:
                driver: "local"
        nextapps:
                driver: "local"
        nextdata:
                driver: "local"
        nextconfig:
                driver: "local"
        db:
                driver: "local"






