---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels: 
    app: test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  revisionHistoryLimit: 15
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: debian
          image: nginx:latest 
          imagePullPolicy: IfNotPresent
          resources: 
            requests:
              cpu: 0.5
              memory: "512Mi"
            limits:
              cpu: 0.8
              memory: "1024Mi"
      imagePullSecrets:
        - name: config-secret

