apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: redis
  labels:
    app: redis
spec:
  # Choose how to expose your service
  type: NodePort
  ports:
    # The port number to expose the service
    - port: 6379
  # Pod to route service traffic  
  selector:
    app: redis
